/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define DEMO_PANEL_RK055AHD091 0
#define DEMO_PANEL_RK055IQH091 1
#define DEMO_PANEL_RK055MHD091A0 2
#define DEMO_PANEL_G1120B0MIPI 3
#define DEMO_PANEL_TFT_PROTO_5 4
#define DEMO_PANEL_RASPI_7INCH 5
#define DEMO_PANEL_ZC143AC72MIPI 6
#define DEMO_PANEL_LCD_PAR_S035 8
#define CONFIG_MCUX_DEMO_PANEL_RK055AHD091_SUPPORT 1
#define CONFIG_MCUX_DEMO_PANEL_RK055IQH091_SUPPORT 1
#define CONFIG_MCUX_DEMO_PANEL_RK055MHD091A0_SUPPORT 1
#define CONFIG_MCUX_DEMO_PANEL_G1120B0MIPI_SUPPORT 1
#define CONFIG_MCUX_DEMO_PANEL_TFT_PROTO_5_SUPPORT 1
#define CONFIG_MCUX_DEMO_PANEL_RASPI_7INCH_SUPPORT 1
#define CONFIG_MCUX_DEMO_PANEL_ZC143AC72MIPI_SUPPORT 1
#define CONFIG_MCUX_DEMO_PANEL_LCD_PAR_S035_SUPPORT 1
#define CONFIG_CPU_CORTEX_M 1
#define CONFIG_FLASH_BASE_ADDRESS 0x28000000
#define CONFIG_FLASH_DEFAULT_APP_OFFSET 0x0
#define CONFIG_HAS_FLASH_LOAD_OFFSET 1
#define CONFIG_FLASH_LOAD_OFFSET 0x0
// #define CONFIG_FLASH_DRIVER_EXECUTES_FROM_RAM 0
// #define CONFIG_ENABLE_QUICKACCESS_SECTION_IN_XSPI_DRIVER 0
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0

#endif /* _MCUX_CONFIG_H_ */
